# Generated by Django 6.0.2 on 2026-03-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_schoolelection_schoolyearelection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolyearelection',
            name='end_date',
        ),
    ]
