# Generated by Django 6.0.2 on 2026-03-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_semester_students', '0002_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
