# Generated by Django 6.0.2 on 2026-03-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current_semester_students', '0003_student_voted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='student_school_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='year_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='voted',
        ),
    ]
