# Generated by Django 6.0.2 on 2026-03-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_schoolelection_election_election_available_and_more'),
        ('voting_history', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolElection',
            new_name='SchoolYearElection',
        ),
    ]
