# Generated by Django 6.0.2 on 2026-03-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=255)),
                ('school_election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.schoolelection')),
            ],
        ),
    ]
