# Generated by Django 6.0.2 on 2026-03-14 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('current_semester_students', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('seat_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='candidate_images/')),
                ('description', models.TextField(blank=True)),
                ('link', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current_semester_students.student')),
                ('partylist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='running_candidates.partylist')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_candidates.position')),
            ],
        ),
    ]
