# Generated by Django 6.0.2 on 2026-03-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_semester_students', '0004_rename_student_id_student_student_school_id_and_more'),
        ('running_candidates', '0001_initial'),
        ('voters', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current_semester_students.student')),
            ],
        ),
        migrations.CreateModel(
            name='VoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_candidates.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='running_candidates.position')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voters.vote')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
