# Generated by Django 6.0.2 on 2026-03-08 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('start_voting_date', models.DateField()),
                ('end_voting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('academic_year', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
    ]
