# Generated by Django 6.0.2 on 2026-03-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current_semester_students', '0001_initial'),
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolelection',
            name='election',
        ),
        migrations.AddField(
            model_name='election',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='election',
            name='school_election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.schoolelection'),
        ),
        migrations.CreateModel(
            name='CoursesValidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='current_semester_students.course')),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
        migrations.CreateModel(
            name='YearLevelValidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_level', models.SmallIntegerField()),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.election')),
            ],
        ),
    ]
