# Generated by Django 6.0.2 on 2026-03-22 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('running_candidates', '0001_initial'),
        ('voting', '0004_remove_schoolyearelection_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylist',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.schoolyearelection'),
        ),
        migrations.AddField(
            model_name='position',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voting.election'),
        ),
    ]
